## DataSource
#spring.datasource.url= jdbc:mysql://haza.cktovlso2ukh.ap-northeast-1.rds.amazonaws.com:3306/DEVHAZA?autoReconnect=true
#spring.datasource.username= root
#spring.datasource.password= roothaza123
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



spring:
  profiles.active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    username:
    password:

  # Security OAuth
  security:
    oauth2.client:
      registration:
        google:
          clientId: 638736893171-6qr36je3jc1dilt8lqa05ijn53vm8nnl.apps.googleusercontent.com
          clientSecret: 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
          scope:
            - email
            - profile

#            facebook:
#                clientId: '{???? client-id}'
#                clientSecret: '{???? client-secret}'
#                scope:
#                    - email
#                    - public_profile
#
#            naver:
#                clientId: '{??? client-id}'
#                clientSecret: '{??? client-secret}'
#                clientAuthenticationMethod: post
#                authorizationGrantType: authorization_code
#                redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
#                scope:
#                    - nickname
#                    - email
#                    - profile_image
#                clientName: Naver
#
#            kakao:
#                clientId: '{??? client-id}'
#                clientSecret: '{??? client-secret}'
#                clientAuthenticationMethod: post
#                authorizationGrantType: authorization_code
#                redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
#                scope:
#                    - profile_nickname
#                    - profile_image
#                    - account_email
#                    clientName: Kakao

# Provider ??
#provider:
#naver:
#authorizationUri: https://nid.naver.com/oauth2.0/authorize
#tokenUri: https://nid.naver.com/oauth2.0/token
#userInfoUri: https://openapi.naver.com/v1/nid/me
#userNameAttribute: response
#kakao:
#authorizationUri: https://kauth.kakao.com/oauth/authorize
#tokenUri: https://kauth.kakao.com/oauth/token
#userInfoUri: https://kapi.kakao.com/v2/user/me
#userNameAttribute: id

# cors ??
cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

# jwt secret key ??
jwt.secret: 'VEhJUy1ERVZIQVpBLUpXVFRPS0VOLURFQVRILWRrYW5qZmtnb2RpZWhsZndsIGFoZm1ycFRlayBmZHp6d2hybWEgV0tmcWRtc3Jqcmt4ZG1zbFJL'

# ?? ?? secret Key ? RedirectUri ??
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect



